name: money
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  flutter_tags: ^1.0.0-nullsafety.1
  flutter_hooks: ^0.20.1
  flutter_animate: ^4.5.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0

  # Otros paquetes
  flutter_riverpod: ^2.5.1
  go_router: ^13.1.0
  intl: ^0.19.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_radar: ^3.12.4
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/interests/